---
- hosts: drbd_group
  become: true
  vars:
    etc_hosts_add_all_hosts: true
    pri_domain_name: fritz.box 
  roles:
    - role: robertdebock.lvm
    - role: ansible-ntp
    - role: ansible-etc-hosts
    - role: drbd
