---
lvm_volume_groups:
  - name: nfs_ng 
    pvs:
      - /dev/sdb
      - /dev/sdc

lvm_logical_volumes:
  - name: ha_nfs_internal_lv 
    vg: nfs_ng 
    size: 20 
      #opts: --type cache-pool
      #
  - name: ha_nfs_exports_lv
    vg: nfs_ng
    size: 100%FREE 

drbd_common:
  disk: ''
  net: |
    cram-hmac-alg sha1;
    shared-secret "{{ drbd_network_shared_secret }}";
  handlers: ''
  startup: ''
  options: ''

drbd_disks:
  - device: /dev/drbd0
    disk: /dev/sdb 
    filesystem: ext4
    partitions: 1
    mountpoint: /opt/nfs
    mountopts: defaults
    resource: r0
    state: present
    use_partition: /dev/sdb1

drbd_group: drbd

drbd_interface: eth0

drbd_network_shared_secret: wXE8MqVa

drbd_vip: 192.168.178.245

drbd_use_heartbeat: false
drbd_use_parted: true


drbd_deb_packages: ['drbd-utils','linux-modules-extra-{{ ansible_kernel }}']

# Toggle
drbd_unicast_mode: false
drbd_unicast_port: 694

